# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/

################################################################################

includes:
- ../app_locations.yml
- ../engine_locations.yml
- ./tk-multi-loader2.yml
- ./tk-multi-breakdown.yml
- ./tk-multi-publish2.yml
- ./tk-multi-screeningroom.yml
- ./tk-multi-shotgunpanel.yml
- ./tk-multi-snapshot.yml
- ./tk-multi-workfiles2.yml

################################################################################

# asset
settings.tk-clarisse.asset:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.clarisse"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.clarisse.project"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  debug_logging: false
  location: "@engines.tk-clarisse.location"

# asset_step
settings.tk-clarisse.asset_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-breakdown: "@settings.tk-multi-breakdown.clarisse"
    tk-multi-loader2: "@settings.tk-multi-loader2.clarisse"
    tk-multi-publish2: "@settings.tk-multi-publish2.clarisse.asset_step"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.clarisse"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.clarisse.asset_step"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.clarisse.asset_step"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-snapshot, name: Snapshot...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  template_project: asset_work_area_clarisse
  location: "@engines.tk-clarisse.location"

# project
settings.tk-clarisse.project:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.clarisse"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.clarisse.project"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  debug_logging: true
  location: "@engines.tk-clarisse.location"

# sequence
settings.tk-clarisse.sequence:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.clarisse.project"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-clarisse.location"

# sequence_step
settings.tk-clarisse.sequence_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-breakdown: "@settings.tk-multi-breakdown.clarisse"
    tk-multi-setframerange:
      location:
        type: git_branch
        branch: enable_hooks_for_app
        path: https://github.com/diegogarciahuerta/tk-multi-setframerange
        version: b24a977
      hook_frame_operation: "{engine}/tk-multi-setframerange/frame_operations_tk-clarisse.py"

    # tk-multi-loader2: "@settings.tk-multi-loader2.clarisse"
    tk-multi-publish2: "@settings.tk-multi-publish2.clarisse.sequence_step"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.clarisse"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.clarisse.sequence_step"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.clarisse.sequence_step"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-snapshot, name: Snapshot...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  template_project: sequence_work_area_clarisse
  location: "@engines.tk-clarisse.location"

# shot
settings.tk-clarisse.shot:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.clarisse.project"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-clarisse.location"

# shot_step
settings.tk-clarisse.shot_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-breakdown: "@settings.tk-multi-breakdown.clarisse"
    tk-multi-setframerange:
      location:
        type: git_branch
        branch: enable_hooks_for_app
        path: https://github.com/diegogarciahuerta/tk-multi-setframerange
        version: b24a977
      hook_frame_operation: "{engine}/tk-multi-setframerange/frame_operations_tk-clarisse.py"
    tk-multi-loader2: "@settings.tk-multi-loader2.clarisse"
    tk-multi-publish2: "@settings.tk-multi-publish2.clarisse.shot_step"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.clarisse"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.clarisse.shot_step"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.clarisse.shot_step"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-snapshot, name: Snapshot...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  template_project: shot_work_area_clarisse
  location: "@engines.tk-clarisse.location"
