# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your tk-app yaml configuration file, as
# THIS FILE BY ITSELF WILL NOT WORK 
# These are the additions to get clarisse engine up and running with the 
# default tk-apps for this environment

# clarisse
settings.tk-multi-loader2.clarisse:
  actions_hook: '{engine}/tk-multi-loader2/tk-clarisse_actions.py'
  action_mappings:
    Alembic Cache: [reference, import]
    Obj File: [import]
    Lwo File: [import]
    Lws File: [import]
    Image: [texture_node, texture_stream_node, import]
    Clarisse Project File: [reference, import]
    Vdb File: [import]
  entities:
  - caption: Assets
    entity_type: Asset
    filters:
    - [project, is, "{context.project}"]
    hierarchy: [sg_asset_type, code]
  - caption: Shots
    entity_type: Shot
    filters:
    - [project, is, "{context.project}"]
    hierarchy: [sg_sequence, code]
  - caption: My Tasks
    entity_type: Task
    filters:
    - [task_assignees, is, "{context.user}"]
    - [project, is, "{context.project}"]
    hierarchy: [entity, content]
  publish_filters: [["sg_status_list", "is_not", null]]
  location: "@apps.tk-multi-loader2.location"
