# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your templates.yml configuration file, as
# THIS FILE BY ITSELF WILL NOT WORK 
# These are the additions to get clarisse engine up and running with the 
# default tk-apps for this environment

paths:
    #
    # Clarisse
    #

    # asset
    # define the location of a work area
    asset_work_area_clarisse:
        definition: '@asset_root/work/clarisse'
        root_name: 'primary'
    # define the location of a publish area
    asset_publish_area_clarisse:
        definition: '@asset_root/publish/clarisse'
        root_name: 'primary'

    # The location of WIP files
    clarisse_asset_work:
        definition: '@asset_root/work/clarisse/{name}.v{version}.project'
        root_name: 'primary'
    # The location of backups of WIP files
    clarisse_asset_snapshot:
        definition: '@asset_root/work/clarisse/snapshots/{name}.v{version}.{timestamp}.project'
        root_name: 'primary'
    # The location of published clarisse files
    clarisse_asset_publish:
        definition: '@asset_root/publish/clarisse/{name}.v{version}.project'
        root_name: 'primary'
 
    # shot 
    # define the location of a work area
    shot_work_area_clarisse:
        definition: '@shot_root/work/clarisse'
        root_name: 'primary'
    # define the location of a publish area
    shot_publish_area_clarisse:
        definition: '@shot_root/publish/clarisse'
        root_name: 'primary'
    # The location of WIP files
    clarisse_shot_work:
        definition: '@shot_root/work/clarisse/{name}.v{version}.project'
        root_name: 'primary'
    # The location of backups of WIP files
    clarisse_shot_snapshot:
        definition: '@shot_root/work/clarisse/snapshots/{name}.v{version}.{timestamp}.project'
        root_name: 'primary'
    # The location of published clarisse files
    clarisse_shot_publish:
        definition: '@shot_root/publish/clarisse/{name}.v{version}.project'
        root_name: 'primary'

    # sequence 
    # define the location of a work area
    sequence_work_area_clarisse:
        definition: '@sequence_root/work/clarisse'
        root_name: 'primary'
    # define the location of a publish area
    sequence_publish_area_clarisse:
        definition: '@sequence_root/publish/clarisse'
        root_name: 'primary'
    # The location of WIP files
    clarisse_sequence_work:
        definition: '@sequence_root/work/clarisse/{name}.v{version}.project'
        root_name: 'primary'
    # The location of backups of WIP files
    clarisse_sequence_snapshot:
        definition: '@sequence_root/work/clarisse/snapshots/{name}.v{version}.{timestamp}.project'
        root_name: 'primary'
    # The location of published clarisse files
    clarisse_sequence_publish:
        definition: '@sequence_root/publish/clarisse/{name}.v{version}.project'
        root_name: 'primary'
